### ISSUE TITLE
anyway to make this for chromebook

### ISSUE THREAD

**Issue by Snipperrazer** [Lamby777/CRX-Retriever#1]
Possibly make this for chromebook

**Comment by Lamby777** [comment]
I wrote this in Python, but I could try rewriting it a separate web version in JavaScript or TypeScript. The only issue is that I don't have an unmanaged Chromebook to test it on, but it should work alright.

**Comment by Lamby777** [comment]
Alright, it's done! Slightly less convenient in terms of downloading and having to rename files and unzipping them and all of that, but it's a lot more user-friendly and allows for pasting pre-written lists in case your friend or teacher wants to give you a list of stuff to download. I didn't want to use a CORS proxy, because that would defeat the whole purpose of working through school filters, since schools often filter proxies.

[HTML Preview](https://htmlpreview.github.io/?https://github.com/Lamby777/CRX-Fetcher/blob/master/index.html)
[Source Code](https://github.com/Lamby777/CRX-Fetcher)
